// Generated by CoffeeScript 1.3.3
(function() {
  var CountryCapital;

  CountryCapital = (function() {

    function CountryCapital(country_data) {
      this.country_data = country_data;
      this.answers = {};
      this.country = '';
      this.capital = '';
    }

    CountryCapital.prototype.random = function(length) {
      return Math.floor(Math.random() * length);
    };

    CountryCapital.prototype.ask = function() {
      var countries, country, index;
      countries = Object.keys(this.country_data);
      index = this.random(countries.length);
      country = countries[index];
      this.country = this.country_data[country];
      this.capital = this.country.capital;
      return $('#question').html("What is the capital of " + country + "?");
    };

    return CountryCapital;

  })();

  jQuery(function() {
    var country_capital;
    country_capital = new CountryCapital(country_data);
    country_capital.ask();
    $('#submit').click(function() {
      if ($('#capital').val() === country_capital.capital) {
        $('#answer').css({
          color: 'green'
        }).html('CORRECT');
        console.log(country_capital.country.latitude);
        return load_map(country_capital.country.latitude, country_capital.country.longitude);
      } else {
        return $('#answer').css({
          color: 'red'
        }).html('INCORRECT');
      }
    });
    return $('#next').click(function() {
      return country_capital.ask();
    });
  });

}).call(this);
